version: '3.7'

services:
  app:
    container_name: adm_videos_app
    build:
      context: ../../
      dockerfile: Dockerfile.dev
    #    rodando a aplicacao disponibilizada no docker hub
    #    image: jkavdev/fc3-admin-catalogo-de-videos-java:main-31
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "8080:8080"
    networks:
      - adm_videos_network
      - adm_videos_services

networks:
  adm_videos_network:
  adm_videos_services:
    external: true