# To build and run:
# docker build -f Dockerfile.dev -t fc3-catalogo .
# docker run fc3-catalogo

# build stage
FROM gradle:7.6.1-jdk17-alpine AS builder

WORKDIR /usr/app/

COPY . .

RUN gradle bootJar

# build runtime
FROM eclipse-temurin:17.0.5_8-jre-alpine

# copiando o jar gerado para a imagem
COPY --from=builder /usr/app/build/libs/*.jar /opt/app/application.jar

# criando grupo e um usuario, para que nao seja executado criado um container com o usuario root
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

# rodando jar da aplicacao
CMD java -jar /opt/app/application.jar